# Generated by Django 2.1.1 on 2018-11-08 15:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181108_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='creat_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='creat_date',
        ),
        migrations.AddField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 8, 15, 47, 19, 159288, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 8, 15, 47, 19, 158812, tzinfo=utc)),
        ),
    ]
